name: Pull request validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  call-workflow:
    uses: compulim/workflows/.github/workflows/pull-request-validation.yml@main
    with:
      package-name: react-wrap-with
      skip-integration-test: true
