name: Pull request validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  call-workflow:
    strategy:
      matrix:
        switch: [current, node-16, node-17, node-18]
    uses: compulim/workflows/.github/workflows/pull-request-validation.yml@main
    with:
      package-name: react-wrap-with
      skip-integration-test: false
      switch: ${{ matrix.switch }}
